keys:
  - &padraic age1sartew6ntahhyg06p72rpy77xuyw0gh28zp76ynl3na3v73l7ufqjm5sd5
  - &Hydrogen age1arrfttxu8v0873mr22xmmdn0mjretm8n3kgtks55c3e5s2wd23kq6vmypx
  # - &Oxygen age1ag9ev5har8qvzvcy2ls29wgwxsq6v32myrspcssaq4nt2xwtgvpqpx3wh7
  # - &nixos age17upq8al832e9vmk7m2ymwc8hhxdjmj5twzavekzczgg56h0a8eeq2wauq4
  # - &Nitrogen age1qdr25peulwhzwvy6x73aytlfgmkxdya84at7v4q5ka6s6ecv9ygs28vzzh
creation_rules:
  - path_regex: nixos/Hydrogen/secrets.yaml$
    key_groups:
    - age:
      - *padraic
      - *Hydrogen
  # - path_regex: hosts/Oxygen/secrets.yaml$
  #   key_groups:
  #   - age:
  #     - *padraic
  #     - *Oxygen
  # - path_regex: hosts/Nitrogen/secrets.yaml$
  #   key_groups:
  #   - age:
  #     - *nixos
  #     - *Nitrogen
